### ISSUE TITLE
Bug - ConcurrentModificationException during startup phase

### ISSUE THREAD

**Issue by DivineThreepwood** [CentralLabFacilities/rct-java#1]
Exception occurs when requesting transformations during startup phase. 

```java
FATAL EXCEPTION: pool-6-thread-1
 Process: org.openbase.bco.bcomfy, PID: 24699
 java.util.ConcurrentModificationException
     at java.util.HashMap$HashIterator.remove(HashMap.java:805)
     at rct.impl.TransformerCoreDefault.checkRequests(TransformerCoreDefault.java:675)
     at rct.impl.TransformerCoreDefault.access$000(TransformerCoreDefault.java:26)
     at rct.impl.TransformerCoreDefault$1.run(TransformerCoreDefault.java:232)
     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
     at java.lang.Thread.run(Thread.java:818)
```

**Comment by DivineThreepwood** [comment]
Was fixed long time ago. Why still open???
