### ISSUE TITLE
Transformer Exception 

### ISSUE THREAD

**Issue by lilischroeder** [CentralLabFacilities/rct-java#2]
```
final Future<Transform> transform = Registries.getLocationRegistry().getUnitTransformation(unitConfig, Registries.getLocationRegistry().getRootLocationConfig());
```
This call throws the following exception. (unitConfig is of type UnitType.COLORABLE_LIGHT)
```
rct.TransformerException: Transform contains nan: Transform[parent:Bath; child:SLamp2; time:1498496774867; transform:{NaN NaN NaN 1.00; NaN NaN NaN 1.50; NaN NaN NaN 0.00; 0.00 0.00 0.00 1.00}]
	at rct.impl.TransformerCoreDefault.setTransform(TransformerCoreDefault.java:196)
	at rct.impl.TransformerCoreDefault.newTransformAvailable(TransformerCoreDefault.java:900)
	at rct.impl.rsb.TransformCommunicatorRSB.transformCallback(TransformCommunicatorRSB.java:207)
	at rsb.eventprocessing.SingleThreadEventReceivingStrategy$DispatchThread.run(SingleThreadEventReceivingStrategy.java:98)
```

**Comment by nkoester** [comment]
There is no Registry or UnitType in RCT. Please report upstream in the used wrapper.
