### ISSUE TITLE
ConcurrentModificationException

### ISSUE THREAD

**Issue by pLeminoq** [CentralLabFacilities/rct-java#5]
Sometimes rct fails with the following concurrentModificationException:

<pre>
org.openbase.jul.exception.FatalImplementationErrorException: Fatal implementation error in or by using Thread[pool-14-thread-3,5,main]: UncaughtException found!
	at org.openbase.jul.schedule.AbstractExecutorService$1.uncaughtException(AbstractExecutorService.java:91)
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1057)
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1052)
	at java.lang.Thread.dispatchUncaughtException(Thread.java:1956)
Caused by: java.util.ConcurrentModificationException: null
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1437)
	at java.util.HashMap$KeyIterator.next(HashMap.java:1461)
	at rct.impl.rsb.TransformCommunicatorRSB.publishCache(TransformCommunicatorRSB.java:236)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
</pre>

**Comment by DivineThreepwood** [comment]
This concurrent modification exception occurs if transformations is send before the initial sync phase has been finished.
